backend:
  name: github
  repo: johnchourajr/socalcoffee
  branch: master
  site_domain: socalcoffee.netlify.com
media_folder: "_uploads"
collections:
  - name: "recipes"
    label: "Recipes"
    folder: "_recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Background, name: background, widget: image}
      - {label: Ratio, name: ratio, widget: string}
      - {label: Function, name: function, widget: string}
      - label: Ingredients
        name: ingredients
        widget: list
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Value, name: value, widget: string}
          - {label: Type, name: type, widget: string}
          - {label: Class, name: class, widget: string}
      - label: Equipment
        name: equipment
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}
      - label: Steps
        name: short_steps
        widget: list
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Text, name: text, widget: string}
          - {label: Number, name: number, widget: string}
          - {label: Class, name: class, widget: string}
  - name: "losangeles"
    label: "Los Angeles"
    folder: "_losangeles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "orange"
    label: "Orange"
    folder: "_orange"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "riverside"
    label: "Riverside"
    folder: "_riverside"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "sanbernardino"
    label: "San Bernardino"
    folder: "_sanbernardino"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "sandiego"
    label: "San Diego"
    folder: "_sandiego"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "santabarbara"
    label: "Santa Barbara"
    folder: "_santabarbara"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
  - name: "ventura"
    label: "Ventura"
    folder: "_ventura"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Shop Name, name: shop_name, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Yelp ID, name: yelp_id, widget: string}
      - {label: Type, name: type, widget: select, default: Coffee Shop, options: [Coffee Shop, Coffee Shop & Roaster, Coffee Roaster, Pop Up Coffee Shop]}
      - {label: Tags, name: tags, widget: list}
      - {label: Coffee, name: coffee, widget: list}
      - {label: Map, name: map, widget: string}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Featured Primary, name: featured_max_1, widget: boolean, required: false}
      - {label: Featured Secondary, name: featured_min, widget: boolean, required: false}
